name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: string
jobs:
  CI:
    permissions: write-all
    name: print-token
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Calculate Version Number
      id: calc_version
      run: |
        version="v1.0.${{ github.run_number }}"
        echo "Calculated version: $version"
        echo "::set-output name=version::$version"
